// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1) {
  return window['go']['service']['AuthService']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['service']['AuthService']['Register'](arg1);
}
