// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Login(arg1:Record<string, string>):Promise<model.LoginResponse>;

export function Register(arg1:Record<string, string>):Promise<model.User>;
