// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['service']['CategoryService']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['service']['CategoryService']['DeleteCategory'](arg1);
}

export function GetAllCategories() {
  return window['go']['service']['CategoryService']['GetAllCategories']();
}

export function GetCategory(arg1) {
  return window['go']['service']['CategoryService']['GetCategory'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['service']['CategoryService']['UpdateCategory'](arg1);
}
