// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateCategory(arg1:model.Category):Promise<model.CategoryResponse>;

export function DeleteCategory(arg1:number):Promise<model.CategoryResponse>;

export function GetAllCategories():Promise<model.CategoryListResponse>;

export function GetCategory(arg1:number):Promise<model.CategoryResponse>;

export function UpdateCategory(arg1:model.Category):Promise<model.CategoryResponse>;
