// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveDocument(arg1, arg2) {
  return window['go']['service']['DocumentService']['ApproveDocument'](arg1, arg2);
}

export function CreateDocument(arg1) {
  return window['go']['service']['DocumentService']['CreateDocument'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['service']['DocumentService']['DeleteDocument'](arg1);
}

export function GetAllDocuments() {
  return window['go']['service']['DocumentService']['GetAllDocuments']();
}

export function GetDocument(arg1) {
  return window['go']['service']['DocumentService']['GetDocument'](arg1);
}

export function UpdateDocument(arg1) {
  return window['go']['service']['DocumentService']['UpdateDocument'](arg1);
}
