// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ApproveDocument(arg1:number,arg2:number):Promise<model.DocumentResponse>;

export function CreateDocument(arg1:model.Document):Promise<model.DocumentResponse>;

export function DeleteDocument(arg1:number):Promise<model.DocumentResponse>;

export function GetAllDocuments():Promise<model.DocumentListResponse>;

export function GetDocument(arg1:number):Promise<model.DocumentResponse>;

export function UpdateDocument(arg1:model.Document):Promise<model.DocumentResponse>;
