// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEquipment(arg1) {
  return window['go']['service']['EquipmentService']['CreateEquipment'](arg1);
}

export function DeleteEquipment(arg1) {
  return window['go']['service']['EquipmentService']['DeleteEquipment'](arg1);
}

export function GetAllEquipment() {
  return window['go']['service']['EquipmentService']['GetAllEquipment']();
}

export function GetEquipment(arg1) {
  return window['go']['service']['EquipmentService']['GetEquipment'](arg1);
}

export function GetEquipmentByLocation(arg1) {
  return window['go']['service']['EquipmentService']['GetEquipmentByLocation'](arg1);
}

export function GetEquipmentBySupplier(arg1) {
  return window['go']['service']['EquipmentService']['GetEquipmentBySupplier'](arg1);
}

export function UpdateEquipment(arg1) {
  return window['go']['service']['EquipmentService']['UpdateEquipment'](arg1);
}
