// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLocation(arg1) {
  return window['go']['service']['LocationService']['CreateLocation'](arg1);
}

export function DeleteLocation(arg1) {
  return window['go']['service']['LocationService']['DeleteLocation'](arg1);
}

export function GetAllLocations() {
  return window['go']['service']['LocationService']['GetAllLocations']();
}

export function GetLocation(arg1) {
  return window['go']['service']['LocationService']['GetLocation'](arg1);
}

export function GetLocationByEquipment(arg1) {
  return window['go']['service']['LocationService']['GetLocationByEquipment'](arg1);
}

export function UpdateLocation(arg1) {
  return window['go']['service']['LocationService']['UpdateLocation'](arg1);
}
