// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateLocation(arg1:model.Location):Promise<model.LocationResponse>;

export function DeleteLocation(arg1:number):Promise<model.LocationResponse>;

export function GetAllLocations():Promise<model.LocationListResponse>;

export function GetLocation(arg1:number):Promise<model.LocationResponse>;

export function GetLocationByEquipment(arg1:number):Promise<model.LocationListResponse>;

export function UpdateLocation(arg1:model.Location):Promise<model.LocationResponse>;
