// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateMovement(arg1:model.Movement):Promise<model.MovementResponse>;

export function DeleteMovement(arg1:number):Promise<model.MovementResponse>;

export function GetAllMovements():Promise<model.MovementListResponse>;

export function GetMovement(arg1:number):Promise<model.MovementResponse>;

export function GetMovementsByEquipment(arg1:number):Promise<model.MovementListResponse>;

export function GetMovementsByLocation(arg1:number):Promise<model.MovementListResponse>;

export function UpdateMovement(arg1:model.Movement):Promise<model.MovementResponse>;
