// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMovement(arg1) {
  return window['go']['service']['MovementService']['CreateMovement'](arg1);
}

export function DeleteMovement(arg1) {
  return window['go']['service']['MovementService']['DeleteMovement'](arg1);
}

export function GetAllMovements() {
  return window['go']['service']['MovementService']['GetAllMovements']();
}

export function GetMovement(arg1) {
  return window['go']['service']['MovementService']['GetMovement'](arg1);
}

export function GetMovementsByEquipment(arg1) {
  return window['go']['service']['MovementService']['GetMovementsByEquipment'](arg1);
}

export function GetMovementsByLocation(arg1) {
  return window['go']['service']['MovementService']['GetMovementsByLocation'](arg1);
}

export function UpdateMovement(arg1) {
  return window['go']['service']['MovementService']['UpdateMovement'](arg1);
}
