// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateSupplier(arg1:model.Supplier):Promise<model.SupplierResponse>;

export function DeleteSupplier(arg1:number):Promise<model.SupplierResponse>;

export function GetAllSuppliers():Promise<model.SupplierListResponse>;

export function GetSupplier(arg1:number):Promise<model.SupplierResponse>;

export function GetSupplierByEquipment(arg1:number):Promise<model.SupplierListResponse>;

export function UpdateSupplier(arg1:model.Supplier):Promise<model.SupplierResponse>;
