// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSupplier(arg1) {
  return window['go']['service']['SupplierService']['CreateSupplier'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['service']['SupplierService']['DeleteSupplier'](arg1);
}

export function GetAllSuppliers() {
  return window['go']['service']['SupplierService']['GetAllSuppliers']();
}

export function GetSupplier(arg1) {
  return window['go']['service']['SupplierService']['GetSupplier'](arg1);
}

export function GetSupplierByEquipment(arg1) {
  return window['go']['service']['SupplierService']['GetSupplierByEquipment'](arg1);
}

export function UpdateSupplier(arg1) {
  return window['go']['service']['SupplierService']['UpdateSupplier'](arg1);
}
