// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Delete(arg1:number):Promise<model.Response_tohaboy_internal_model_User_>;

export function GetByID(arg1:number):Promise<model.Response_tohaboy_internal_model_User_>;

export function GetByName(arg1:string):Promise<model.Response_tohaboy_internal_model_User_>;

export function GetCurrentUser():Promise<model.Response_tohaboy_internal_model_User_>;

export function GetUser(arg1:string):Promise<model.Response_tohaboy_internal_model_User_>;

export function Update(arg1:model.User):Promise<model.Response_tohaboy_internal_model_User_>;
