// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['service']['UserService']['Delete'](arg1);
}

export function GetByID(arg1) {
  return window['go']['service']['UserService']['GetByID'](arg1);
}

export function GetByName(arg1) {
  return window['go']['service']['UserService']['GetByName'](arg1);
}

export function GetCurrentUser() {
  return window['go']['service']['UserService']['GetCurrentUser']();
}

export function GetUser(arg1) {
  return window['go']['service']['UserService']['GetUser'](arg1);
}

export function Update(arg1) {
  return window['go']['service']['UserService']['Update'](arg1);
}
